// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		int c1 = 0, c2 = 0;
	    for (int i = 0; i < N; i++) {
			if (Math.random() > 0.5)
				c1++;
			else
				c2++;
		}
		System.err.println("> 0.5: " + c1 + " times");
		System.err.println("<= 0.5: " + c2 + " times");
		if (c2 > 0)
			System.out.println("Ratio: " + ((double)c1)/c2);
	}
}
